//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YIP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Цех
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Цех()
        {
            this.Печатная_продукция = new HashSet<Печатная_продукция>();
        }
    
        public int Номер_цеха { get; set; }
        public string Название_цеха { get; set; }
        public string Начальник_цеха { get; set; }
        public Nullable<int> Телефон_цеха { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Печатная_продукция> Печатная_продукция { get; set; }
    }
}
